name: database
description: The database layer for Monolith.
version: 1.0.0
repository: https://github.com/monolith-game/database

environment:
  sdk: ^3.1.0-262.3.beta

dependencies:
  crypt: ^4.3.0
  drift: ^2.11.0
  sqlite3: ^2.1.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.11.0
  lints: ^2.0.0
  test: ^1.21.0
